specVersion: 1.0.0
name: stable-asset-subql
version: 0.0.0
description: Stable Asset
repository: 'https://github.com/subquery/karura-subql-starter'
schema:
  file: ./schema.graphql
network:
  endpoint: 'wss://acala-polkadot.api.onfinality.io/public-ws'
  genesisHash: '0xfc41b9bd8ef8fe53d58c7ea67c794c7ec9a73daf05e6d54b14ff6342c99ba64c'
  dictionary: 'https://api.subquery.network/sq/subquery/acala-dictionary'
  chaintypes:
    file: ./dist/chaintypes.js
dataSources:
  - kind: substrate/Runtime
    startBlock: 1072384 # Time stable asset is first propsed
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleMint
          kind: substrate/EventHandler
          filter:
            module: stableAsset
            method: Minted
        - handler: handleSwap
          kind: substrate/EventHandler
          filter:
            module: stableAsset
            method: TokenSwapped
        - handler: handleProportionRedeem
          kind: substrate/EventHandler
          filter:
            module: stableAsset
            method: RedeemedProportion
        - handler: handleSingleRedeem
          kind: substrate/EventHandler
          filter:
            module: stableAsset
            method: RedeemedSingle
        - handler: handleMultiRedeem
          kind: substrate/EventHandler
          filter:
            module: stableAsset
            method: RedeemedMulti
