specVersion: 0.2.0
name: stable-asset-subql
version: 0.0.4
description: Stable Asset
repository: 'https://github.com/subquery/karura-subql-starter'
schema:
  file: ./schema.graphql
network:
  endpoint: 'wss://karura.api.onfinality.io/public-ws'
  genesisHash: '0xbaf5aabe40646d11f0ee8abbdc64f4a4b7674925cba08e4a05ff9ebed6e2126b'
  dictionary: 'https://api.subquery.network/sq/subquery/karura-dictionary'
  chaintypes:
    file: ./dist/chaintypes.js
dataSources:
  - kind: substrate/Runtime
    startBlock: 1
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleBlock
          kind: substrate/BlockHandler
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: balances
            method: Deposit
        - handler: handleCall
          kind: substrate/CallHandler
